version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: user-management-mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: USER_MANAGEMENT
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
